Added Identity Function for Math lib
Hedgehog-Computing/math pull request #37
Opened 2022-05-08 19:02 UTC by MudroadWhite

[Identity Function](https://github.com/Hedgehog-Computing/math/issues/6):
> identity(n) (creates 2-d identity matrix with nxn size)

2022-05-08 23:26 UTC, lidangzzz reviewed
Hi here are my reviews. Let me know if you have any other questions. Thx.

2022-05-08 23:26 UTC, lidangzzz commented on identity.hhs
> +	if (input == 0) {
Please use "===" instead of "==" in JS/Hedgeghog Script

2022-05-08 23:26 UTC, lidangzzz commented on identity.hhs
> +	if (input == 1) {
Use "===" instead of "=="

2022-05-08 23:26 UTC, lidangzzz commented on identity.hhs
> +		result += row;
use push() instead of "+="

2022-05-08 23:26 UTC, lidangzzz commented on identity.hhs
> +}
1. Create an N-by-N matrix instead of creating an N-by-N array and use constructure of Matrix, which copy the data twice;
2. Unit test is needed.

2022-05-10 03:14 UTC, Gaoooooo requested changes

2022-05-10 03:14 UTC, Gaoooooo commented on identity.hhs
> +
Requesting changes based on this or Lidangzzz input

2022-05-12 05:04 UTC, Gaoooooo commented
Everything after these changes will look perfect. I think your way is faster than the mathjs way, as you dont have to copy twice and dont have to convert to Mat and back nor make a call to mathjs library. Will merge after these small issues are fixed - thank you!

2022-05-13 13:28 UTC, Gaoooooo requested changes
sorry i accidentally left these in pending changes

2022-05-24 02:42 UTC, merged

2022-05-24 02:43 UTC, Gaoooooo commented
Good job, I apologize for the late merge, I thought I merged it earlier.